In [11]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [4]:
data = np.random.randint(0,100,(10,2))

In [5]:
data

array([[58, 50],
       [31, 68],
       [40, 38],
       [45, 34],
       [63, 62],
       [ 5, 10],
       [52,  6],
       [48, 31],
       [45, 94],
       [95, 62]])

In [6]:
scaler_model = MinMaxScaler()
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scaler_model.fit(data)

/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [9]:
scaler_model.transform(data) # normalizing data max num->1, min num->0 

array([[0.58888889, 0.5       ],
       [0.28888889, 0.70454545],
       [0.38888889, 0.36363636],
       [0.44444444, 0.31818182],
       [0.64444444, 0.63636364],
       [0.        , 0.04545455],
       [0.52222222, 0.        ],
       [0.47777778, 0.28409091],
       [0.44444444, 1.        ],
       [1.        , 0.63636364]])

In [13]:
mydata = np.random.randint(0,100,(10,5))
mydata

array([[ 3, 97, 61, 27, 76],
       [19, 20, 22, 12, 20],
       [58, 84, 30, 53, 24],
       [56, 65, 99, 18, 21],
       [ 0, 32,  4, 39, 91],
       [56, 49, 55, 55, 70],
       [29, 48, 90, 83, 16],
       [63, 35, 14, 26, 58],
       [ 5, 80, 43, 73, 84],
       [65, 87, 43, 88, 56]])

In [18]:
df = pd.DataFrame(mydata,columns=['f1','f2','f3','f4','label'])
df

f1  f2  f3  f4  label
0   3  97  61  27     76
1  19  20  22  12     20
2  58  84  30  53     24
3  56  65  99  18     21
4   0  32   4  39     91
5  56  49  55  55     70
6  29  48  90  83     16
7  63  35  14  26     58
8   5  80  43  73     84
9  65  87  43  88     56

In [23]:
X = df[['f1','f2','f3','f4']]

In [20]:
y = df['label']

In [24]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=101)

In [30]:
X_train.shape

(8, 4)

In [31]:
X_train

f1  f2  f3  f4
0   3  97  61  27
4   0  32   4  39
9  65  87  43  88
3  56  65  99  18
5  56  49  55  55
7  63  35  14  26
6  29  48  90  83
1  19  20  22  12

In [32]:
X_test.shape

(2, 4)

In [33]:
X_test

f1  f2  f3  f4
8   5  80  43  73
2  58  84  30  53